### ISSUE TITLE
Install Harmonix without AWS Route 53

### ISSUE THREAD

**Issue by tdiaque** [awslabs/harmonix#109]
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

Our team is looking into deploying Harmonix for AWS as we had previously POCed Backstage before moving to AWS for our Platform.
I see in the installation instructions that we need to create & configure a hosted zone (Route 53).

Is this a hard requirement or can AWS Harmonix be installed without Route 53?

#### Provide a link to the example/module related to the question

N/A

#### Additional context

N/A

**Comment by z-sourcecode** [comment]
Hi @tdiaque Thanks for reaching out. 
It's not a hard requirement. However, because we deploy both backstage and GitLab securely we need a valid domain to create a certificate to allow secure connection(SSL).  We use a single certificate for both apps (sub-domains).

If you wish to deploy Harmonix with your own certificate you can edit the platform IAC to import your existing certificate rather than creating one:

https://github.com/awslabs/harmonix/blob/558792058098e38f57dccbb9e19063f0d9e57a51/iac/roots/opa-common-constructs/src/hostedzone-construct.ts#L38
